name: Deploy assets/readme to WordPress.org
on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  deploy-to-trunk:
    name: Deploy assets/readme to trunk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Test SVN credentials
        run: |
          SVN_URL="https://plugins.svn.wordpress.org/tinypress/"
          svn info $SVN_URL --username "$SVN_USERNAME" --password "$SVN_PASSWORD"
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      - name: Remove assets from deployment, we can add directly if we need new ones (avoid permission issues)
        run: |
          rm -rf $GITHUB_WORKSPACE/.wordpress-org/assets
          echo "Removed .wordpress-org/assets from deployment"

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: tinypress
          IGNORE_OTHER_FILES: true
